import { CLIENT_ERROR } from '@shopby/shared';

export default {
  '/product-detail': (code) => {
    const noReloadCodes = [
      CLIENT_ERROR.NOT_SELECTED_OPTION,
      CLIENT_ERROR.NOT_INSERTED_REQUIRED_TEXT_OPTION,
      CLIENT_ERROR.OPTION_FAIL_DUPLICATE_OPTION,
      CLIENT_ERROR.OPTION_FAIL_INVALID_COUNT,
      CLIENT_ERROR.FORBIDDEN_ARTICLE,
      CLIENT_ERROR.REVIEW_FAIL_HAS_NO_CONTENT,
      CLIENT_ERROR.PRODUCT_INQUIRY_FAIL_HAS_NO_CONTENT,
      CLIENT_ERROR.PRODUCT_INQUIRY_FAIL_HAS_NO_TITLE,
      CLIENT_ERROR.INQUIRY_FAIL_HAS_NO_TITLE,
      CLIENT_ERROR.INQUIRY_FAIL_HAS_NO_CONTENT,
    ];
    return !noReloadCodes.includes(code);
  },
  '/cart': () => true,
};
