openapi: 3.0.1
info:
  title: marketing-server
  description: 샵바이 마케팅 Server to Server API
  version: '1.0'
servers:
  - url: https://server-api.e-ncp.com
tags: []
paths:
  /campaigns:
    post:
      tags:
        - Campaign
      summary: 연동정보로 캠페인 수정
      description:
        "\n외부 연동정보로 캠페인을 수정합니다.\n\n**현재는 shop by의 상점번호를 이용한 수정만 가능합니다.**\n\
        \n## request\n\n- godosno: shop by 상점번호\n- status: 변경할 캠페인 상태. 중지 요청(PAUSED_BY_SYSTEM)만\
        \ 가능 \n\n## response\n\n- campaignNo: 캠페인 번호\n- name: 캠페인 이름\n- status: 캠페\
        인 상태\n- dailyBudget: 일 단위의 캠페인 평균 예산\n- mallNo: 캠페인이 속한 쇼핑몰 번호\n- startDate:\
        \ 캠페인 시작일(yyyy-MM-dd)\n- startDateTime: 캠페인 시작일시(yyyy-MM-ddTHH:mm:ss)\n- endDate:\
        \ 캠페인 종료일(yyyy-MM-dd)\n- endDateTime: 캠페인 종료일시(yyyy-MM-ddTHH:mm:ss)\n\n##\
        \ Enums\n\n### status\n- PENDING: 대기중\n- PAUSED_BY_SYSTEM: 중지됨(시스템에 의한 강제\
        \ 중지)\n- PAUSED: 중지됨\n- ENABLED: 진행중\n- PENDING_BY_PRODUCT: 상품 연동 대기중\n- READY:\
        \ 준비중\n- REMOVED: 삭제\n"
      operationId: campaign-post-update
      parameters:
        - name: Version
          in: header
          description: API 버전
          required: true
          schema:
            type: string
          example: '1.0'
        - name: systemKey
          in: header
          description: API 연동 키
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/campaigns869981354'
            examples:
              campaign-post-update:
                value: '{"godosno":12345,"status":"PAUSED_BY_SYSTEM"}'
      responses:
        '200':
          description: '200'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/campaigns1904911364'
              examples:
                campaign-post-update:
                  value: "{\"campaignNo\":1,\"name\":\"system default name\",\"status\"\
                    :\"PAUSED_BY_SYSTEM\",\"dailyBudget\":10000,\"mallNo\":1,\"startDateTime\"\
                    :\"2020-08-01T00:00:00\",\"endDateTime\":\"2020-08-31T23:59:59\"\
                    ,\"startDate\":\"2020-08-01\",\"endDate\":\"2020-08-31\"}"
  /marketing/display:
    put:
      tags:
        - Marketing
      summary: 마케팅 상품 일괄 노출여부 변경
      description: "## 부가설명 및 특이사항\n            \n마케팅 상품 일괄 노출여부 변경\n"
      operationId: 마케팅 상품 노출설정 일괄 변경하기
      parameters:
        - name: systemKey
          in: header
          description:
            "\n 시스템 키 (외부시스템 연동을 위한 server API 호출 키)\n - 발급경로: 워크스페이스> 셀러\
            어드민> 신규 앱(App) 등록 시 수정페이지에서 확인가능 \n - 앱 기준으로 systemKey 발급됨\n"
          required: true
          schema:
            type: string
          example: test-system-key
        - name: Authorization
          in: header
          description:
            "\n \n 인증토큰 (Bearer 전달받은 토큰)\n \n - 형식: Bearer + 발급받은 access_token\n\
            \n - 발급경로: POST /auth/token 또는 POST /auth/token/long-lived 의 응답 값으로 내려온\
            \ access_token\n"
          required: false
          schema:
            type: string
          example: Bearer ABCDERAdjflaskjdfosiaetlkfs
        - name: partnerId
          in: header
          description:
            "\n 파트너 아이디 (파트너사 로그인계정)\n \n ※ server API 호출하는 기존 방식으로, 향후 fade\
            \ out될 수 있습니다.<br>\n\n Authorization을 입력을 통한 serverAPI 호출방식 권장드립니다.<br>\n\
            \n (Authorization 입력했을 경우, partnerId와 mallKey는 null로 보내시길 바랍니다.)<br>\n\n\
            \n"
          required: false
          schema:
            type: string
          example: testpartner
        - name: mallKey
          in: header
          description:
            " 외부 API 연동키 (외부시스템연동 코드)\n \n ※ server API 호출하는 기존 방식으로, 향후\
            \ fade out될 수 있습니다.<br>\n\n Authorization을 입력을 통한 serverAPI 호출방식 권장드립니다\
            .<br>\n\n (Authorization 입력했을 경우, partnerId와 mallKey는 null로 보내시길 바랍니다.)<br>\n\
            \n\n "
          required: false
          schema:
            type: string
          example: 각 어드민에서 복사된 값
        - name: Version
          in: header
          description: API 버전
          required: true
          schema:
            type: string
          example: '1.0'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/marketing-display-1028540568'
            examples:
              마케팅 상품 노출설정 일괄 변경하기:
                value: "{\"exposureProducts\":[{\"productNo\":1,\"displayable\":true,\"\
                  channelType\":\"FACEBOOK\"}]}"
      responses:
        '204':
          description: '204'
  /marketing/product:
    put:
      tags:
        - Marketing
      summary: 마케팅 상품 등록/수정하기
      description:
        "## 부가설명 및 특이사항\n            \n마케팅 상품 등록/수정하기\n\n ## 부가설명 및 특이사\
        항\n * channelType NAVER_SHOPPING 인 경우에만 additionalInfo 정보 기입 가능합니다.\n * 도서\
        \ 카테고리인 상품은, 네이버 포인트 적립 불가합니다.\n  \n"
      operationId: 마케팅 상품 등록/수정하기
      parameters:
        - name: systemKey
          in: header
          description:
            "\n 시스템 키 (외부시스템 연동을 위한 server API 호출 키)\n - 발급경로: 워크스페이스> 셀러\
            어드민> 신규 앱(App) 등록 시 수정페이지에서 확인가능 \n - 앱 기준으로 systemKey 발급됨\n"
          required: true
          schema:
            type: string
          example: test-system-key
        - name: Authorization
          in: header
          description:
            "\n \n 인증토큰 (Bearer 전달받은 토큰)\n \n - 형식: Bearer + 발급받은 access_token\n\
            \n - 발급경로: POST /auth/token 또는 POST /auth/token/long-lived 의 응답 값으로 내려온\
            \ access_token\n"
          required: false
          schema:
            type: string
          example: Bearer ABCDERAdjflaskjdfosiaetlkfs
        - name: partnerId
          in: header
          description:
            "\n 파트너 아이디 (파트너사 로그인계정)\n \n ※ server API 호출하는 기존 방식으로, 향후 fade\
            \ out될 수 있습니다.<br>\n\n Authorization을 입력을 통한 serverAPI 호출방식 권장드립니다.<br>\n\
            \n (Authorization 입력했을 경우, partnerId와 mallKey는 null로 보내시길 바랍니다.)<br>\n\n\
            \n"
          required: false
          schema:
            type: string
          example: testpartner
        - name: mallKey
          in: header
          description:
            " 외부 API 연동키 (외부시스템연동 코드)\n \n ※ server API 호출하는 기존 방식으로, 향후\
            \ fade out될 수 있습니다.<br>\n\n Authorization을 입력을 통한 serverAPI 호출방식 권장드립니다\
            .<br>\n\n (Authorization 입력했을 경우, partnerId와 mallKey는 null로 보내시길 바랍니다.)<br>\n\
            \n\n "
          required: false
          schema:
            type: string
          example: 각 어드민에서 복사된 값
        - name: Version
          in: header
          description: API 버전
          required: true
          schema:
            type: string
          example: '1.0'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/marketing-product273182022'
            examples:
              마케팅 상품 등록/수정하기:
                value: "{\"mallNo\":2173,\"productNo\":1,\"displayable\":true,\"channelType\"\
                  :\"NAVER_SHOPPING\",\"additionalInfo\":{\"categoryId\":\"categoryId\"\
                  ,\"priceComparePageId\":\"priceComparePageId\",\"saleType\":\"RENTAL\"\
                  ,\"productStatus\":\"NEW\",\"isCrossBorderShipping\":true,\"isParallelImport\"\
                  :false,\"isCustomOrder\":false,\"hasExtraCharge\":false,\"naverPayAvailableLocations\"\
                  :[],\"naverPayAccumLocations\":[\"PC\",\"MOBILE\"],\"brandCertificateYn\"\
                  :\"N\",\"epCode\":\"\",\"monthlyRentalFee\":null,\"rentalContractPeriod\"\
                  :null}}"
      responses:
        '204':
          description: '204'
  /marketing/products/settings:
    get:
      tags:
        - Marketing
      summary: 상품 번호로 네이버 쇼핑 설정 정보 조회하기
      description:
        "## 부가설명 및 특이사항\n            \n상품 번호로 네이버 쇼핑 설정 정보 조회하는 API 입니다\
        .\n\n상품 번호는 최대 200개 까지 조회 가능합니다.\n"
      operationId: 상품 번호로 네이버 쇼핑 설정 정보 조회하기
      parameters:
        - name: productNos
          in: query
          description: 상품 번호
          required: true
          schema:
            type: number
          example: '10000001,10000002'
        - name: systemKey
          in: header
          description:
            "\n 시스템 키 (외부시스템 연동을 위한 server API 호출 키)\n - 발급경로: 워크스페이스> 셀러\
            어드민> 신규 앱(App) 등록 시 수정페이지에서 확인가능 \n - 앱 기준으로 systemKey 발급됨\n"
          required: true
          schema:
            type: string
          example: test-system-key
        - name: Authorization
          in: header
          description:
            "\n \n 인증토큰 (Bearer 전달받은 토큰)\n \n - 형식: Bearer + 발급받은 access_token\n\
            \n - 발급경로: POST /auth/token 또는 POST /auth/token/long-lived 의 응답 값으로 내려온\
            \ access_token\n"
          required: false
          schema:
            type: string
          example: Bearer ABCDERAdjflaskjdfosiaetlkfs
        - name: partnerId
          in: header
          description:
            "\n 파트너 아이디 (파트너사 로그인계정)\n \n ※ server API 호출하는 기존 방식으로, 향후 fade\
            \ out될 수 있습니다.<br>\n\n Authorization을 입력을 통한 serverAPI 호출방식 권장드립니다.<br>\n\
            \n (Authorization 입력했을 경우, partnerId와 mallKey는 null로 보내시길 바랍니다.)<br>\n\n\
            \n"
          required: false
          schema:
            type: string
          example: testpartner
        - name: mallKey
          in: header
          description:
            " 외부 API 연동키 (외부시스템연동 코드)\n \n ※ server API 호출하는 기존 방식으로, 향후\
            \ fade out될 수 있습니다.<br>\n\n Authorization을 입력을 통한 serverAPI 호출방식 권장드립니다\
            .<br>\n\n (Authorization 입력했을 경우, partnerId와 mallKey는 null로 보내시길 바랍니다.)<br>\n\
            \n\n "
          required: false
          schema:
            type: string
          example: 각 어드민에서 복사된 값
        - name: Version
          in: header
          description: API 버전
          required: true
          schema:
            type: string
          example: '1.0'
      responses:
        '200':
          description: '200'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/marketing-products-settings1592297693'
              examples:
                상품 번호로 네이버 쇼핑 설정 정보 조회하기:
                  value: "{\"marketingProductSettings\":[{\"productNo\":10000001,\"\
                    additionalInfo\":{}},{\"productNo\":10000002,\"additionalInfo\"\
                    :{}}]}"
components:
  schemas:
    campaigns869981354:
      type: object
      properties:
        godosno:
          type: number
          description: 연동정보(고도 상점번호)
          example: 12345
        status:
          type: string
          description: 캠페인 상태
          example: PAUSED_BY_SYSTEM
      description: ''
    marketing-products-settings1592297693:
      type: object
      properties:
        marketingProductSettings:
          type: array
          description: "네이버 쇼핑 설정 상품^|[MarketingProductSettings(productNo=10000001,\
            \ additionalInfo={}), MarketingProductSettings(productNo=10000002, additionalInfo={})]"
          items:
            type: object
            properties:
              additionalInfo:
                type: object
                description: 네이버 쇼핑 추가 정보
                example: '{}'
              productNo:
                type: number
                description: 상품 번호 리스트
                example: 10000001
      description: ''
    marketing-display-1028540568:
      type: object
      properties:
        exposureProducts:
          type: array
          description: ''
          items:
            type: object
            properties:
              displayable:
                type: string
                description: '노출 여부(미노출시 ep, 카탈로그 노출 안됨)'
                example: 'true'
              channelType:
                type: string
                description: '마케팅 타입(FACEBOOK, NAVER_SHOPPING)'
                example: FACEBOOK
              productNo:
                type: string
                description: 상품 번호
                example: '1'
      description: ''
    campaigns1904911364:
      type: object
      properties:
        startDateTime:
          type: string
          description: 캠페인 시작일시
          example: 2020-08-01T00:00
        endDate:
          type: string
          description: 캠페인 종료일
          example: 2020-08-31
        dailyBudget:
          type: number
          description: 일 단위의 캠페인 평균 예산
          example: 10000
        name:
          type: string
          description: 캠페인 이름
          example: system default name
        endDateTime:
          type: string
          description: 캠페인 종료일시
          example: 2020-08-31T23:59:59
        mallNo:
          type: number
          description: 캠페인이 속한 쇼핑몰 번호
          example: 1
        campaignNo:
          type: number
          description: 캠페인 번호
          example: 1
        startDate:
          type: string
          description: 캠페인 시작일
          example: 2020-08-01
        status:
          type: string
          description: 캠페인 상태
          example: PAUSED_BY_SYSTEM
      description: ''
    marketing-product273182022:
      type: object
      properties:
        additionalInfo:
          type: object
          properties:
            isParallelImport:
              type: boolean
              description: 병행수입
              example: false
            brandCertificateYn:
              type: string
              description: 브랜드 인증상품 여부(Y/N)
              example: 'N'
            isCrossBorderShipping:
              type: boolean
              description: 해외구매대행
              example: true
            monthlyRentalFee:
              type: string
              description: 네이버 쇼핑 월 렌탈료
              example: 'null'
            naverPayAvailableLocations:
              type: string
              description: '네이버 페이 사용 가능 표시([PC, MOBILE])'
              example: '[]'
            saleType:
              type: string
              description:
                "판매방식 구분 (NONE, WHOLESALE, RENTAL, LENT, INSTALLMENT, RESERVATION_SALE,\
                \ SUBSTITUTION, RESERVATION_BUY)"
              example: RENTAL
            productStatus:
              type: string
              description: '상품상태 (NEW, USED, REFURB, DISPLAY, RETURN, SCRATCH)'
              example: NEW
            priceComparePageId:
              type: string
              description: 가격비교 페이지 ID
              example: priceComparePageId
            isCustomOrder:
              type: boolean
              description: 주문제작
              example: false
            naverPayAccumLocations:
              type: string
              description: '네이버페이 적립 가능 표시([PC, MOBILE])'
              example: '[PC, MOBILE]'
            hasExtraCharge:
              type: boolean
              description: 별도 설치비 있음
              example: false
            epCode:
              type: string
              description: ep관리코드
              example: ''
            rentalContractPeriod:
              type: string
              description: 네이버 쇼핑 렌탈 계약 기간
              example: 'null'
            categoryId:
              type: string
              description: 네이버 카테고리 ID
              example: categoryId
          description: 네이버쇼핑 추가 정보
        displayable:
          type: string
          description: 마케팅채널에 노출 여부
          example: 'true'
        channelType:
          type: string
          description: '마케팅 채널 타입(NAVER_SHOPPING, FACEBOOK)'
          example: NAVER_SHOPPING
        mallNo:
          type: number
          description: 쇼핑몰 번호
          example: 2173
        productNo:
          type: number
          description: 상품 번호
          example: 1
      description: ''
